import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'HF Open API',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="relative">
        <div className="z-50 fixed top-0 w-full bg-slate-800 text-slate-100 text-center p-1">
          USE IT OR LOSE IT 
        </div>
	<div className="mt-8">
          {children}
	</div>
      </body>
    </html>
  )
}
