import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'HF Open API',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="bg-slate-800 text-slate-100 text-center p-1">
          USE IT OR LOSE IT 
        </div>
        {children}
      </body>
    </html>
  )
}
